apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-istio
  namespace: one
spec:
  podSelector: # Apply to all pods
    matchLabels:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          operator.istio.io/component: Base